[package]
name = "tangled_actors"
version = "0.2.0"
edition = "2024"

license = "MIT OR Apache-2.0"
repository = "https://github.com/IntQuant/tangled-actors"
categories = ["concurrency", ]
description = "Yet another macro-based actor crate"

[dependencies]
tangled_actors_macros = {version="0.2.0", path = "../tangled_actors_macros"}
thiserror = "2.0.20"
tokio = {version="1.53.1", features=["sync", "rt"]}
tracing = "0.1.44"
eframe = { version = "0.36.1", default-features=false, optional = true }

[features]
eframe = ["dep:eframe"]
docs = ["eframe/wayland"]

[dev-dependencies]
eyre = "0.6.12"
tokio = {version="1.53.1", features=["macros", "rt-multi-thread", "time"]}
eframe = { version = "0.36.1" }

[[example]]
name = "eframe_app"
required-features = ["eframe"]

[package.metadata.docs.rs]
features = ["docs", "eframe"]
