[package]
name = "tangled_actors"
version = "0.1.0"
edition = "2024"

[dependencies]
tangled_actors_macros = {path = "../tangled_actors_macros"}
thiserror = "2.0.20"
tokio = {version="1.53.1", features=["sync", "rt"]}
tracing = "0.1.44"

[dev-dependencies]
eyre = "0.6.12"
tokio = {version="1.53.1", features=["macros", "rt-multi-thread", "time"]}
